# Generated by Django 6.0.6 on 2026-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_commission_percentage_product_allow_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('OUT_OF_STOCK', 'Out Of Stock'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=20),
        ),
    ]
