# Generated by Django 5.2.7 on 2026-09-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_deduction_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Restocking/return fee deducted from customer refund amount', max_digits=10),
        ),
    ]
