# Generated by Django 5.2.7 on 2026-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_return_deduction_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_access_instructions',
            field=models.TextField(blank=True, help_text='Custom instructions or message displayed to buyer after purchasing digital product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file_name',
            field=models.CharField(blank=True, help_text='Legacy single digital file name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file_url',
            field=models.URLField(blank=True, help_text='Legacy single digital file URL', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_resources',
            field=models.JSONField(blank=True, default=list, help_text='List of digital files and external video/resource links attached to this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_unlimited_stock',
            field=models.BooleanField(default=False, help_text='If true, product stock is unlimited (useful for digital products)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('DIGITAL', 'Digital Product')], default='PHYSICAL', max_length=20),
        ),
    ]
