# Generated by Django 5.2.7 on 2026-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_digital_access_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_store',
            field=models.BooleanField(default=True, help_text="If true, product is displayed on supplier's public storefront page"),
        ),
    ]
