# Generated by Django 5.2.7 on 2026-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_show_in_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_in_store',
            field=models.BooleanField(default=True, help_text='If true, product is listed publicly on supplier web store. If false, accessible only via direct link or DM.'),
        ),
    ]
