# Generated by Django 5.2.7 on 2026-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_instagramaccount_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
