# Generated by Django 6.0.6 on 2026-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_systemsettings_user_has_extended_trial_user_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
