# Generated by Django 6.0.6 on 2026-07-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='cancellation_policy',
            field=models.TextField(blank=True, default='NOT ACCEPTED', null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='cod_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='return_policy',
            field=models.TextField(blank=True, default='NOT ACCEPTED', null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='store_banner',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='store_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='store_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SellerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('SUBMITTED', 'Documents Submitted'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('is_card_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
