# Generated by Django 6.0.6 on 2026-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_websitesettings_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
