# Generated by Django 6.0.6 on 2026-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_websitesettings_online_payment_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='cancellation_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='return_policy',
            field=models.BooleanField(default=False),
        ),
    ]
