# Generated by Django 6.0.6 on 2026-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_websitesettings_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
