# Generated by Django 6.0.6 on 2026-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_websitesettings_online_payment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='terms_of_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
