# Generated by Django 6.0.6 on 2026-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_websitesettings_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_token_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='token_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
