# Generated by Django 5.2.7 on 2026-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_instagramaccount_is_token_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redeemed_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_paid_reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
