# Generated by Django 5.2.7 on 2026-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_redeemed_months_user_referral_paid_reward_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator_vip',
            field=models.BooleanField(default=False),
        ),
    ]
