# Generated by Django 5.2.7 on 2026-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_is_creator_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_code_set',
            field=models.BooleanField(default=False),
        ),
    ]
