# Generated by Django 5.2.7 on 2026-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_custom_code_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_purchase_count',
            field=models.IntegerField(default=0),
        ),
    ]
