# Generated by Django 5.2.7 on 2026-09-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_pro_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
