# Generated by Django 5.2.7 on 2026-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_creator_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_following_official_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='official_follow_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='official_follow_points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='official_unfollow_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
