# Generated by Django 5.2.7 on 2026-09-05 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_is_following_official_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInBioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('banner_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('theme_id', models.CharField(default='glass_monochrome', max_length=50)),
                ('custom_theme', models.JSONField(blank=True, default=dict)),
                ('social_accounts', models.JSONField(blank=True, default=list)),
                ('social_display_mode', models.CharField(default='icons_top', max_length=30)),
                ('smart_redirect_enabled', models.BooleanField(default=True)),
                ('smart_input_placeholder', models.CharField(default='Paste your Reel URL here...', max_length=255)),
                ('smart_input_button_text', models.CharField(default='Get Link', max_length=50)),
                ('smart_input_title', models.CharField(default='Have a Reel or Promo Link?', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_in_bio_pages', to='accounts.instagramaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_in_bio_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkInBioBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('link', 'Standard Link'), ('header', 'Heading / Text'), ('video', 'Embedded Video'), ('image', 'Image Banner'), ('social_group', 'Social Links Group'), ('smart_redirect', 'Smart Redirect Box'), ('product_card', 'Product Showcase'), ('file_download', 'File Download'), ('contact_card', 'Contact Information'), ('custom_button', 'Custom Action Button')], default='link', max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=2000)),
                ('media_url', models.URLField(blank=True, default='', max_length=2000)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='accounts.linkinbiopage')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkInBioRedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('input_match_url', models.CharField(max_length=1000)),
                ('match_type', models.CharField(choices=[('reel_code', 'Reel / Post Shortcode (Auto)'), ('exact', 'Exact URL Match'), ('contains', 'Contains Keyword / Substring')], default='reel_code', max_length=20)),
                ('destination_type', models.CharField(choices=[('url', 'Destination Website URL'), ('file', 'File / Download'), ('product', 'Specific Product'), ('message', 'Custom Popup Message')], default='url', max_length=30)),
                ('destination_value', models.TextField()),
                ('destination_title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hits_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='accounts.linkinbiopage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkInBioAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('block_click', 'Block Click'), ('redirect_hit', 'Smart Redirect Used'), ('social_click', 'Social Icon Click')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.linkinbioblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='accounts.linkinbiopage')),
                ('redirect_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.linkinbioredirectrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
