# Generated by Django 5.2.7 on 2026-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_linkinbiopage_linkinbioblock_linkinbioredirectrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_program_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
