# Generated by Django 5.2.7 on 2026-09-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_creator_program_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='razorpay_stakeholder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
