# Generated by Django 5.2.7 on 2026-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_sellerkyc_razorpay_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='payout_hold_mode',
            field=models.CharField(choices=[('INSTANT', 'Instant Payouts'), ('MONTHLY', 'Monthly Held Payouts')], default='INSTANT', max_length=20),
        ),
    ]
