# Generated by Django 6.0.6 on 2026-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_websitesettings_payout_hold_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_following_official_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='official_follow_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='official_follow_points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
