# Generated by Django 6.0.6 on 2026-09-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_instagramaccount_is_following_official_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInBioUsernameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(db_index=True, max_length=100)),
                ('deactivated_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_history', to='accounts.linkinbiopage')),
            ],
            options={
                'ordering': ['-deactivated_at'],
            },
        ),
    ]
