# Generated by Django 5.2.7 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_custom_points_per_paid_sub',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
