# Generated by Django 5.2.7 on 2026-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_creator_custom_points_per_paid_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
