# Generated by Django on 2026-09-17

from django.db import migrations, models

def fix_referred_by_set_postgres_type(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ALTER COLUMN referred_by_set TYPE boolean 
                USING (CASE WHEN referred_by_set::text IN ('1', 'true', 't') THEN true ELSE false END);
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_sellerkyc_upi_id'),
    ]

    operations = [
        migrations.RunPython(fix_referred_by_set_postgres_type, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referred_by_set',
            field=models.BooleanField(default=False),
        ),
    ]
