# Generated by Django on 2026-09-18

from django.db import migrations, models

def fix_referral_boolean_types(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ALTER COLUMN referral_paid_reward_given TYPE boolean 
                USING (CASE WHEN referral_paid_reward_given::text IN ('1', 'true', 't') THEN true ELSE false END);
                
                ALTER TABLE accounts_user 
                ALTER COLUMN is_creator_vip TYPE boolean 
                USING (CASE WHEN is_creator_vip::text IN ('1', 'true', 't') THEN true ELSE false END);

                ALTER TABLE accounts_user 
                ALTER COLUMN custom_code_set TYPE boolean 
                USING (CASE WHEN custom_code_set::text IN ('1', 'true', 't') THEN true ELSE false END);

                ALTER TABLE accounts_user 
                ALTER COLUMN has_extended_trial TYPE boolean 
                USING (CASE WHEN has_extended_trial::text IN ('1', 'true', 't') THEN true ELSE false END);

                ALTER TABLE accounts_user 
                ALTER COLUMN is_following_official_account TYPE boolean 
                USING (CASE WHEN is_following_official_account::text IN ('1', 'true', 't') THEN true ELSE false END);
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_fix_referred_by_set_type'),
    ]

    operations = [
        migrations.RunPython(fix_referral_boolean_types, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_paid_reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
