# Generated by Django 5.2.7 on 2026-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='visual_data',
            field=models.JSONField(blank=True, default=dict, help_text='React Flow nodes and edges layout'),
        ),
    ]
