# Generated by Django 5.2.7 on 2026-06-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automationrule_visual_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='automationaction',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='automationcampaign',
            name='global_rate_limit',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='deduplication_enabled',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='deduplication_unique_per',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='deduplication_window_seconds',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='stop_on_match',
        ),
    ]
