# Generated by Django 5.2.7 on 2026-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_automationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='parent_event',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
