# Generated by Django 5.2.7 on 2026-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_automationaction_parent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='attachment_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='dm_format',
            field=models.CharField(blank=True, choices=[('text', 'Plain Text'), ('quick_reply', 'Quick Reply Buttons'), ('generic_template', 'Carousel / Generic Template'), ('button_template', 'Button Template'), ('attachment', 'Media / Attachment')], default='text', max_length=30),
        ),
    ]
