# Generated by Django 6.0.6 on 2026-07-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automationaction_attachment_payload_and_more'),
        ('crm', '0022_customer_order_track_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='rule_type',
            field=models.CharField(choices=[('comment_automation', 'Comment Automation        → comment_event'), ('story_automation', 'Story Automation          → story_reply'), ('dm_automation', 'DM Automation             → dm_event'), ('giveaway_comment', 'Giveaway (Comment)        → comment_event'), ('giveaway_dm', 'Giveaway (DM)             → dm_event'), ('product_inquiry_comment', 'Product Inquiry (Comment) → comment_event'), ('product_inquiry_story', 'Product Inquiry (Story)   → story_reply'), ('product_inquiry_dm', 'Product Inquiry (DM)      → dm_event'), ('media_share_dm', 'Media Share DM            → media_share'), ('user_share_post_dm', 'User Shares Post to DM    → media_share')], max_length=40),
        ),
        migrations.CreateModel(
            name='AutomationFollowerGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='follower_gate', help_text='follower_gate | automation_interaction', max_length=50)),
                ('gained_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_gains', to='crm.customer')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_gains', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-gained_at'],
                'unique_together': {('rule', 'customer')},
            },
        ),
    ]
