# Generated by Django 5.2.7 on 2026-08-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_instagramaccount_is_token_expired_and_more'),
        ('automations', '0006_alter_automationrule_rule_type_and_more'),
        ('products', '0012_alter_product_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('REELS', 'Instagram Reel'), ('IMAGE', 'Image Post'), ('VIDEO', 'Video Post'), ('STORIES', 'Story'), ('CAROUSEL', 'Carousel Post')], default='REELS', max_length=20)),
                ('media_url', models.URLField(help_text='Cloudinary media URL (Video or Image)', max_length=2000)),
                ('cover_url', models.URLField(blank=True, help_text='Optional custom thumbnail cover URL for reels/video', max_length=2000, null=True)),
                ('carousel_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs if post_type is CAROUSEL')),
                ('caption', models.TextField(blank=True, default='', help_text='Post caption with hashtags')),
                ('share_to_feed', models.BooleanField(default=True, help_text='For reels: whether to share to the main profile feed')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Target datetime to publish', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing Container'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('container_id', models.CharField(blank=True, help_text='Creation container ID from Meta', max_length=255, null=True)),
                ('instagram_media_id', models.CharField(blank=True, help_text='Published media ID', max_length=255, null=True)),
                ('instagram_permalink', models.URLField(blank=True, help_text='Instagram permalink to live post', max_length=1000, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publishing failed', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instagram_posts', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='accounts.instagramaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='automations_status_99a1b9_idx')],
            },
        ),
    ]
