# Generated by Django 6.0.6 on 2026-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='automation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-created comment/reply automation settings for this post'),
        ),
    ]
