# Generated by Django 5.2.7 on 2026-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_scheduledpost_automation_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='check_follow_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='show_profile_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='dm_format',
            field=models.CharField(blank=True, choices=[('text', 'Plain Text'), ('quick_reply', 'Quick Reply Buttons'), ('generic_template', 'Carousel / Generic Template'), ('button_template', 'Button Template'), ('attachment', 'Media / Attachment'), ('show_profile', 'Show Profile Link'), ('check_follow', 'Check Follower Status Gate')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='carousel_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of media URLs if post_type is CAROUSEL', null=True),
        ),
    ]
