# Generated by Django 5.2.7 on 2026-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_automationaction_check_follow_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='loop_target_id',
            field=models.CharField(blank=True, help_text='Target action/node ID to loop back to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='dm_format',
            field=models.CharField(blank=True, choices=[('text', 'Plain Text'), ('quick_reply', 'Quick Reply Buttons'), ('generic_template', 'Carousel / Generic Template'), ('button_template', 'Button Template'), ('attachment', 'Media / Attachment'), ('show_profile', 'Show Profile Link'), ('check_follow', 'Check Follower Status Gate'), ('loop_back', 'Loop Back to Previous DM')], default='text', max_length=30),
        ),
    ]
