# Generated by Django 5.2.7 on 2026-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('error', 'Error'), ('running', 'Running')], default='running', max_length=20)),
                ('source_db', models.CharField(blank=True, max_length=50)),
                ('tables_backed_up', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('skipped_tables', models.IntegerField(default=0)),
                ('error_detail', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
