# Generated by Django 6.0.6 on 2026-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.IntegerField(default=14)),
                ('extend_days', models.IntegerField(default=7)),
                ('referral_points', models.IntegerField(default=50)),
                ('points_to_redeem', models.IntegerField(default=100)),
                ('premium_plan_price', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('enable_ai', models.BooleanField(default=True)),
                ('enable_subscription_ai', models.BooleanField(default=False)),
                ('business_gemini_api_key', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
