# Generated by Django 6.0.6 on 2026-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='global_cod_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
