# Generated by Django 5.2.7 on 2026-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemsettings_default_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='official_follow_points',
            field=models.IntegerField(default=50),
        ),
    ]
