# Generated by Django 5.2.7 on 2026-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_systemsettings_official_follow_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='creator_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_min_payout_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_payout_cycle_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_vip_extended_trial_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_vip_max_redemption_months',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_vip_points_per_paid_sub',
            field=models.IntegerField(default=20),
        ),
    ]
