# Generated by Django 5.2.7 on 2026-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_systemsettings_creator_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='creator_commission_default_term_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='creator_vip_default_term_months',
            field=models.IntegerField(default=3),
        ),
    ]
