# Generated by Django 6.0.6 on 2026-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_systemsettings_instant_payout_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='official_instagram_handle',
            field=models.CharField(default='anydm.in', max_length=100),
        ),
    ]
