# Generated by Django 5.2.7 on 2026-09-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_systemsettings_official_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='official_instagram_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='official_instagram_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
