# Generated by Django 5.2.7 on 2026-09-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_systemsettings_official_instagram_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='official_instagram_access_token',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='official_instagram_account_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='official_instagram_handle',
        ),
    ]
