# Generated by Django 5.2.7 on 2026-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_systemsettings_official_instagram_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='creator_commission_points_per_paid_sub',
            field=models.IntegerField(default=0),
        ),
    ]
