# Generated by Django 5.2.7 on 2026-09-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_systemsettings_creator_commission_points_per_paid_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='creator_vip_max_redemption_months',
        ),
    ]
