# Generated by Django 5.2.7 on 2026-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_systemsettings_creator_vip_max_redemption_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_razorpay_payouts_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_razorpay_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='manual_settlement_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
