# Generated by Django 5.2.7 on 2026-06-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='media_id',
            field=models.CharField(blank=True, help_text='Instagram media ID (post/reel/story) this interaction happened on', max_length=255, null=True),
        ),
    ]
