# Generated by Django 5.2.7 on 2026-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_customerinteraction_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instagram_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
