# Generated by Django 5.2.7 on 2026-06-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customer_instagram_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='instagram_thread_id',
        ),
    ]
