# Generated by Django 5.2.7 on 2026-06-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_instagramaccount_last_refreshed_at'),
        ('crm', '0014_remove_customer_instagram_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, default='')),
                ('is_ai_mode_on', models.BooleanField(default=False)),
                ('custom_instructions', models.TextField(blank=True, default='')),
                ('response_style', models.CharField(default='Friendly', max_length=50)),
                ('max_reply_length', models.PositiveIntegerField(default=150)),
                ('max_reply_count', models.PositiveIntegerField(default=50)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_location', models.TextField(blank=True, default='')),
                ('working_hours', models.TextField(blank=True, default='')),
                ('delivery_time', models.TextField(blank=True, default='')),
                ('contact_details', models.TextField(blank=True, default='')),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('products_and_services', models.TextField(blank=True, default='')),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('generic_templates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.instagramaccount')),
            ],
        ),
    ]
