# Generated by Django 5.2.7 on 2026-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_customer_is_ai_enabled_aiassistantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantconfig',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
