# Generated by Django 6.0.6 on 2026-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_aiassistantconfig_last_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
