# Generated by Django 6.0.6 on 2026-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantconfig',
            name='use_business_token',
            field=models.BooleanField(default=False),
        ),
    ]
