# Generated by Django 6.0.6 on 2026-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_order_shipping_district_order_shipping_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='waiting_for_order_id',
            field=models.BooleanField(default=False),
        ),
    ]
