# Generated by Django 6.0.6 on 2026-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_customer_waiting_for_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_track_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
