# Generated by Django 5.2.7 on 2026-09-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_sellerkyc_upi_id'),
        ('crm', '0022_customer_order_track_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='creator_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='accounts.creatorcommission'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_type',
            field=models.CharField(choices=[('PRODUCT_ORDER', 'Product Order'), ('CREATOR_COMMISSION', 'Creator Affiliate Commission')], default='PRODUCT_ORDER', max_length=30),
        ),
        migrations.AddField(
            model_name='settlement',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='transfer_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Bank/UPI Transfer'), ('RAZORPAY_ROUTE', 'Razorpay Route (Automated)'), ('RAZORPAY_PAYOUT', 'Razorpay Payouts API')], default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='settlement',
            name='utr_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='crm.order'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Admin Paid Seller'), ('COMPLETED', 'Completed'), ('FAILED', 'Payout Failed')], default='PENDING', max_length=20),
        ),
    ]
