# Generated by Django 5.2.7 on 2026-09-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_settlement_creator_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='payout_mode',
            field=models.CharField(choices=[('INSTANT', 'Instant Payout'), ('MONTHLY', 'Monthly Held')], default='INSTANT', max_length=20),
        ),
    ]
