# Generated by Django 5.2.7 on 2026-09-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_settlement_payout_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_deduction_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
