# Generated by Django 5.2.7 on 2026-09-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_sellerkyc_upi_id'),
        ('crm', '0025_order_return_deduction_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instagram_profile_pic',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instagram_scoped_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_scoped_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_profile_pic', models.URLField(blank=True, max_length=1000, null=True)),
                ('saved_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('saved_shipping_address', models.TextField(blank=True, null=True)),
                ('saved_shipping_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('saved_shipping_place', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_shipping_district', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_shipping_state', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='crm.customer')),
                ('instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sessions', to='accounts.instagramaccount')),
            ],
        ),
    ]
