tunnel: 581546da-4698-416a-8bef-a5f349941ef0
credentials-file: /etc/cloudflared/581546da-4698-416a-8bef-a5f349941ef0.json

ingress:
  - hostname: localapi.locanydm.online
    service: http://web-dev:8004

  - hostname: api.locanydm.online
    service: http://web:8005

  - hostname: wb.locanydm.online
    service: http://webhook:8006

  - service: http_status:404
