from django.urls import path
from .views import (
    FirebaseLoginView, 
    InstagramLoginView, 
    ToggleInstagramLoginView, 
    GetConnectedInstagramAccountsView,
    UpdateProfileView,
    InstagramDeauthorizeView,
    InstagramDataDeletionView,
    RemoveInstagramAccountView,
    ToggleInstagramEnabledView,
    SetActiveInstagramAccountView,
    InstagramStoriesView,
    InstagramMediaListView,
    InstagramMediaProxyView,
    WebsiteSettingsView,
    PublicStorefrontView,
    PublicProductDetailView,
    ReferralStatsView,
    SetReferredByView,
    SetCustomReferralCodeView,
    GrantCreatorVIPView,
    SetCreatorRewardTypeView,
    CreatorEarningsView,
    AdminSettleCreatorCommissionView,
    AdminVIPCreatorsListView,
    AdminUsersAnalyticsView,
    ExtendTrialView,
    GlobalSystemSettingsView,
    RedeemPremiumWithPointsView,
    RazorpayCreateOrderView,
    RazorpayVerifyPaymentView,
    ClaimOfficialFollowRewardView,
    UnfollowOfficialRewardView,
    RazorpayWebhookView,
    InstagramRateLimitStatusView,
    LinkInBioSettingsView,
    LinkInBioBlocksView,
    LinkInBioBlocksReorderView,
    LinkInBioRedirectRulesView,
    LinkInBioUsernameCheckView,
    PublicLinkInBioView,
    PublicLinkInBioResolveRedirectView,
    PublicLinkInBioTrackView
)

urlpatterns = [
    path('auth/firebase/', FirebaseLoginView.as_view(), name='firebase-login'),
    path('auth/instagram/', InstagramLoginView.as_view(), name='instagram-login'),
    path('auth/instagram/toggle-login/', ToggleInstagramLoginView.as_view(), name='instagram-toggle-login'),
    path('auth/instagram/accounts/', GetConnectedInstagramAccountsView.as_view(), name='instagram-accounts'),
    path('profile/update/', UpdateProfileView.as_view(), name='profile-update'),
    path('auth/instagram/deauthorize/', InstagramDeauthorizeView.as_view(), name='instagram-deauthorize'),
    path('auth/instagram/delete-data/', InstagramDataDeletionView.as_view(), name='instagram-delete-data'),
    path('auth/instagram/remove/', RemoveInstagramAccountView.as_view(), name='instagram-remove'),
    path('auth/instagram/toggle-enabled/', ToggleInstagramEnabledView.as_view(), name='instagram-toggle-enabled'),
    path('auth/instagram/set-active/', SetActiveInstagramAccountView.as_view(), name='instagram-set-active'),
    path('instagram/rate-limits/', InstagramRateLimitStatusView.as_view(), name='instagram-rate-limits'),
    path('instagram/stories/', InstagramStoriesView.as_view(), name='instagram-stories'),
    path('instagram/media-list/', InstagramMediaListView.as_view(), name='instagram-media-list'),
    path('instagram/proxy-media/', InstagramMediaProxyView.as_view(), name='instagram-media-proxy'),
    path('website-settings/', WebsiteSettingsView.as_view(), name='website-settings'),
    path('public/store/<str:username>/', PublicStorefrontView.as_view(), name='public-storefront'),
    path('public/store/<str:username>/product/<int:product_id>/', PublicProductDetailView.as_view(), name='public-product-detail'),
    
    # Link-in-Bio Endpoints
    path('link-in-bio/', LinkInBioSettingsView.as_view(), name='link-in-bio-settings'),
    path('link-in-bio/blocks/', LinkInBioBlocksView.as_view(), name='link-in-bio-blocks'),
    path('link-in-bio/blocks/<int:block_id>/', LinkInBioBlocksView.as_view(), name='link-in-bio-block-detail'),
    path('link-in-bio/blocks/reorder/', LinkInBioBlocksReorderView.as_view(), name='link-in-bio-blocks-reorder'),
    path('link-in-bio/redirect-rules/', LinkInBioRedirectRulesView.as_view(), name='link-in-bio-redirect-rules'),
    path('link-in-bio/redirect-rules/<int:rule_id>/', LinkInBioRedirectRulesView.as_view(), name='link-in-bio-redirect-rule-detail'),
    path('link-in-bio/check-username/', LinkInBioUsernameCheckView.as_view(), name='link-in-bio-check-username'),
    path('public/link-in-bio/<str:username>/', PublicLinkInBioView.as_view(), name='public-link-in-bio'),
    path('public/link-in-bio/<str:username>/resolve-redirect/', PublicLinkInBioResolveRedirectView.as_view(), name='public-link-in-bio-resolve-redirect'),
    path('public/link-in-bio/<str:username>/track/', PublicLinkInBioTrackView.as_view(), name='public-link-in-bio-track'),

    # Referral & Billing Endpoints
    path('referral/stats/', ReferralStatsView.as_view(), name='referral-stats'),
    path('referral/set-referred-by/', SetReferredByView.as_view(), name='referral-set-referred-by'),
    path('referral/custom-code/', SetCustomReferralCodeView.as_view(), name='referral-custom-code'),
    path('official-follow/claim/', ClaimOfficialFollowRewardView.as_view(), name='official-follow-claim'),
    path('official-follow/unfollow/', UnfollowOfficialRewardView.as_view(), name='official-follow-unfollow'),
    path('admin/grant-creator-vip/', GrantCreatorVIPView.as_view(), name='admin-grant-creator-vip'),
    path('admin/set-creator-type/', SetCreatorRewardTypeView.as_view(), name='admin-set-creator-type'),
    path('admin/settle-creator-commission/', AdminSettleCreatorCommissionView.as_view(), name='admin-settle-creator-commission'),
    path('creator/earnings/', CreatorEarningsView.as_view(), name='creator-earnings'),
    path('admin/vip-creators/', AdminVIPCreatorsListView.as_view(), name='admin-vip-creators'),
    path('admin/users/', AdminUsersAnalyticsView.as_view(), name='admin-users-analytics'),
    path('plan/extend-trial/', ExtendTrialView.as_view(), name='plan-extend-trial'),
    path('settings/system/', GlobalSystemSettingsView.as_view(), name='settings-system'),
    path('plan/redeem-points/', RedeemPremiumWithPointsView.as_view(), name='plan-redeem-points'),
    path('razorpay/create-order/', RazorpayCreateOrderView.as_view(), name='razorpay-create-order'),
    path('razorpay/verify-payment/', RazorpayVerifyPaymentView.as_view(), name='razorpay-verify-payment'),
    path('razorpay/webhook/', RazorpayWebhookView.as_view(), name='razorpay-webhook'),
]

